Apellidos y nombres:

# **Caso 1 -> Reducción de dimensiones: Áreas de actividad económica**

Los datos sobre el Producto Geográfico Bruto (GSP) de los estados de EEUU están disponibles en el archivo **datosGSP.csv** (en millones de dólares). El archivo consiste de 50 filas (una por cada estado) y 14 columnas, la primera contiene el ID del estado y las 13 restantes corresponden a las siguientes áreas de la actividad económica:

* (V2) Agricultura, silvicultura y pesquería
* (V3) Minería
* (V4) Construcción
* (V5) Manufactura (bienes de consumo duradero)
* (V6) Manufactura (bienes no duraderos)
* (V7) Transporte
* (V8) Comunicaciones
* (V9) Electricidad, gas y saneamiento.
* (V10) Comercio mayorista
* (V11) Comercio minorista
* (V12) Fiduciaria, bienes raíces y seguros
* (V13) Servicios
* (V14) Gobierno

*GSP = Gross State Product*

*Gross: se refiere a "bruto", es decir, el valor total sin deducir impuestos o depreciación*

*State: hace referencia al estado (en EE.UU., las divisiones políticas son los "estados")*

*Product: hace referencia a la producción de bienes y servicios*

---

**Instrucciones**:

---



***Agregue comentarios en cada fase, describiendo los pasos que va realizando.***

***Aplique el Análisis de Componentes Principales (PCA) para reducir las dimensiones del dataset, y comente los resultados obtenidos considerando las siguientes partes en su análisis:***

---

## **Lectura de Datos**

### **datosGSP.csv**

In [1]:
import pandas as pd
import numpy as np

In [2]:
datos = pd.read_csv("datosGSP.csv", sep=",", header=None )
print(datos.shape)
datos.head()

(50, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,AL,2016,1474,4144,10397,11734,2878,2836,3587,6259,9781,12694,15996,15395
1,AK,355,5424,983,277,884,2921,489,360,710,1576,2584,2871,4728
2,AZ,1899,1480,6442,12844,3299,3177,2421,3046,6997,11743,21120,22546,14505
3,AR,2886,570,2240,7242,6656,2470,1332,2361,3469,5729,6453,8344,6664
4,CA,20564,5776,31656,86522,47657,25133,24501,17501,65857,85443,218439,222748,110900

In [3]:
datos.columns = ['Estado', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14' ]
datos.head(3)

,Estado,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,AL,2016,1474,4144,10397,11734,2878,2836,3587,6259,9781,12694,15996,15395
1,AK,355,5424,983,277,884,2921,489,360,710,1576,2584,2871,4728
2,AZ,1899,1480,6442,12844,3299,3177,2421,3046,6997,11743,21120,22546,14505

## **Preparación de datos para aplicar PCA**

In [4]:
# Omitimos duplicados
print(datos.shape)
datos.drop_duplicates(inplace=True)
print(datos.shape)

(50, 14)
(50, 14)

In [5]:
datos.dtypes

Estado    object
V2         int64
V3         int64
V4         int64
V5         int64
V6         int64
V7         int64
V8         int64
V9         int64
V10        int64
V11        int64
V12        int64
V13        int64
V14        int64
dtype: object

## **Aplicación de PCA y seleccionamos la cantidad óptima de Componentes**

In [6]:
#

## **Descripción de los resultados de PCA** (describir/interpretar: matrices y gráficos)

In [7]:
#